{
  "repo_name": "mindsdb_mindsdb",
  "issue_id": "5688",
  "issue_description": "# [Bug]: fix tests structure so that users don't need to manually add init files\n\n### Short description of current behavior\n\nIn the process of contributing new ML engines, @sammiller06 has suggested we add `__init__.py` files where needed to avoid `ModuleNotFoundError` errors, which I've confirmed are still happening as of #5454.\r\n\r\nMore context:\r\n\r\n> ### PyTest’s classic ModuleNotFoundError\r\n> I was unable to run the tests in unit/ml_handlers/ on first try as I got the classic “ModuleNotFoundError”. I know from Pytest experience that you need to add __init__.py files to specific subdirectories, but new contributors may find this a confusing blocker. \r\nSuggestion: make sure new contributors can run tests locally without adding their own __init__.py files\r\n\r\n\n\n### Video or screenshots\n\n_No response_\n\n### Expected behavior\n\n_No response_\n\n### How to reproduce the error\n\n_No response_\n\n### Anything else?\n\n_No response_",
  "issue_comments": [
    {
      "id": 1512945719,
      "user": "ZoranPandovski",
      "body": "Open for contributors"
    },
    {
      "id": 1518275732,
      "user": "alemendoza-v",
      "body": "Hello, I'm interested in working on this issue, how can I know where `__init__.py` files are missing?"
    },
    {
      "id": 1518826332,
      "user": "alemendoza-v",
      "body": "Is this issue solved?"
    },
    {
      "id": 1520529184,
      "user": "ashutosh887",
      "body": "I would like to work on this @paxcema "
    },
    {
      "id": 1520605905,
      "user": "paxcema",
      "body": "I think it is partially solved by #5762. \r\n\r\n@alemendoza-v we're assigning you to complete the rest of this task (sorry @ashutosh887, please check for other issues tagged as \"good first issues\"). \r\n\r\n@alemendoza-v try running tests locally with `python -m pytest` from the `tests` directory. You can try particular directories as well by doing `python -m pytest ./path/to/test_file.py`. If any other `__init__.py` files are missing, you will know because of an error that says no tests were collected."
    },
    {
      "id": 1520608644,
      "user": "alemendoza-v",
      "body": "@paxcema Thank you!"
    },
    {
      "id": 1520638883,
      "user": "alemendoza-v",
      "body": "@paxcema I should run pip install -r requirements.txt first right?"
    },
    {
      "id": 1520957395,
      "user": "paxcema",
      "body": "Yes, and also `requirements_test.txt`. Depending on what it is you're testing, it may also require additional dependencies: each DB handler or ML handler will have its own `requirements.txt` file that you should install prior to testing it. However, for the purposes of this issue, I think testing one of each (I recommend whichever ones have the least amount of dependencies) will be enough."
    },
    {
      "id": 1529446868,
      "user": "SebastianJames55",
      "body": "@paxcema no assignee for this issue, can you please assign me?  "
    },
    {
      "id": 1537361432,
      "user": "SebastianJames55",
      "body": "I gave a go to solve this out of curiosity. I followed the above-mentioned comments. \r\n\r\npython -m pytest tests/ -> 17 errors\r\n![initial error](https://user-images.githubusercontent.com/57470688/236665058-6449ba0c-c5a8-4a73-84d1-d777bbaca156.png)\r\n\r\nI added __init__.py file in tests folder. \r\n![utilities module not found](https://user-images.githubusercontent.com/57470688/236665314-6f9ec545-3f60-42b8-8987-5c163763194a.png). \r\n\r\nI understood that this issue is because of my local setup (no venv used due to setup issues). \r\n\r\nIs it fine if I raise the PR for this issue? @paxcema "
    },
    {
      "id": 1640555975,
      "user": "SebastianJames55",
      "body": "@paxcema Since tests are failing & as confirmed by Zoran [here](https://github.com/mindsdb/mindsdb/pull/6166#issuecomment-1607293229), hope its fine to unassign me from this issue so that someone else can have a go at it. \r\n\r\nI'll try other issues. Thank you for the support. "
    },
    {
      "id": 1640571895,
      "user": "paxcema",
      "body": "Thanks for your patience @SebastianJames55, we'll be happy to help you on any other issues that sound interesting to you!"
    },
    {
      "id": 1642070458,
      "user": "SebastianJames55",
      "body": "Thank you @paxcema :)"
    },
    {
      "id": 1702616972,
      "user": "Birger9",
      "body": "Hi! Is this issue still open for contribution? I'm looking for good first issues as I want to contribute to MindDB. @paxcema "
    },
    {
      "id": 1702997239,
      "user": "paxcema",
      "body": "Hi @Birger9, I believe it is but not 100% sure. There are instructions above to replicate the issue. If you run into it, feel free to work on a solution, simply let us know and we can assign you 😄 "
    },
    {
      "id": 1750067839,
      "user": "Ammy076",
      "body": "> ### Short description of current behavior\r\n> In the process of contributing new ML engines, @sammiller06 has suggested we add `__init__.py` files where needed to avoid `ModuleNotFoundError` errors, which I've confirmed are still happening as of #5454.\r\n> \r\n> More context:\r\n> \r\n> > ### PyTest’s classic ModuleNotFoundError\r\n> > I was unable to run the tests in unit/ml_handlers/ on first try as I got the classic “ModuleNotFoundError”. I know from Pytest experience that you need to add **init**.py files to specific subdirectories, but new contributors may find this a confusing blocker.\r\n> > Suggestion: make sure new contributors can run tests locally without adding their own **init**.py files\r\n> \r\n> ### Video or screenshots\r\n> _No response_\r\n> \r\n> ### Expected behavior\r\n> _No response_\r\n> \r\n> ### How to reproduce the error\r\n> _No response_\r\n> \r\n> ### Anything else?\r\n> _No response_\r\n\r\nTo address the issue described, you need to ensure that the `__init__.py` files are present in the appropriate directories so that Python treats them as packages. Here's an example of how you can add these files to the specified subdirectories:\r\n\r\n```bash\r\ntouch unit/ml_handlers/__init__.py\r\n```\r\n\r\nYou can run this command in your project's root directory to create an empty `__init__.py` file in the `unit/ml_handlers/` directory. This will make Python recognize `unit/ml_handlers/` as a package, and you should no longer encounter `ModuleNotFoundError` errors when running tests in that directory.\r\n\r\nRepeat the same process for any other directories that require `__init__.py` files to be added to address similar import issues."
    },
    {
      "id": 1787934134,
      "user": "nguyenbanhducA1K51",
      "body": "Hi @paxcema, I just try to address this issue to get the hang of contributing. It seems like the  file `pytest`  from command `python -m  pytest` is not there, and each subfolder  of ` ./test` already have the `.init` file, so do I miss something ?"
    },
    {
      "id": 1788139971,
      "user": "paxcema",
      "body": "Hey @nguyenbanhducA1K51, looking at the updated `staging` branch of the repo now and you're right. I will close this since it seems to have been solved, tests are being collected correctly now. \r\n\r\nThanks anyway! I encourage you to look for other open issues."
    }
  ],
  "text_context": "# [Bug]: fix tests structure so that users don't need to manually add init files\n\n### Short description of current behavior\n\nIn the process of contributing new ML engines, @sammiller06 has suggested we add `__init__.py` files where needed to avoid `ModuleNotFoundError` errors, which I've confirmed are still happening as of #5454.\r\n\r\nMore context:\r\n\r\n> ### PyTest’s classic ModuleNotFoundError\r\n> I was unable to run the tests in unit/ml_handlers/ on first try as I got the classic “ModuleNotFoundError”. I know from Pytest experience that you need to add __init__.py files to specific subdirectories, but new contributors may find this a confusing blocker. \r\nSuggestion: make sure new contributors can run tests locally without adding their own __init__.py files\r\n\r\n\n\n### Video or screenshots\n\n_No response_\n\n### Expected behavior\n\n_No response_\n\n### How to reproduce the error\n\n_No response_\n\n### Anything else?\n\n_No response_\n\nOpen for contributors\n\nHello, I'm interested in working on this issue, how can I know where `__init__.py` files are missing?\n\nIs this issue solved?\n\nI would like to work on this @paxcema \n\nI think it is partially solved by #5762. \r\n\r\n@alemendoza-v we're assigning you to complete the rest of this task (sorry @ashutosh887, please check for other issues tagged as \"good first issues\"). \r\n\r\n@alemendoza-v try running tests locally with `python -m pytest` from the `tests` directory. You can try particular directories as well by doing `python -m pytest ./path/to/test_file.py`. If any other `__init__.py` files are missing, you will know because of an error that says no tests were collected.\n\n@paxcema Thank you!\n\n@paxcema I should run pip install -r requirements.txt first right?\n\nYes, and also `requirements_test.txt`. Depending on what it is you're testing, it may also require additional dependencies: each DB handler or ML handler will have its own `requirements.txt` file that you should install prior to testing it. However, for the purposes of this issue, I think testing one of each (I recommend whichever ones have the least amount of dependencies) will be enough.\n\n@paxcema no assignee for this issue, can you please assign me?  \n\nI gave a go to solve this out of curiosity. I followed the above-mentioned comments. \r\n\r\npython -m pytest tests/ -> 17 errors\r\n![initial error](https://user-images.githubusercontent.com/57470688/236665058-6449ba0c-c5a8-4a73-84d1-d777bbaca156.png)\r\n\r\nI added __init__.py file in tests folder. \r\n![utilities module not found](https://user-images.githubusercontent.com/57470688/236665314-6f9ec545-3f60-42b8-8987-5c163763194a.png). \r\n\r\nI understood that this issue is because of my local setup (no venv used due to setup issues). \r\n\r\nIs it fine if I raise the PR for this issue? @paxcema \n\n@paxcema Since tests are failing & as confirmed by Zoran [here](https://github.com/mindsdb/mindsdb/pull/6166#issuecomment-1607293229), hope its fine to unassign me from this issue so that someone else can have a go at it. \r\n\r\nI'll try other issues. Thank you for the support. \n\nThanks for your patience @SebastianJames55, we'll be happy to help you on any other issues that sound interesting to you!\n\nThank you @paxcema :)\n\nHi! Is this issue still open for contribution? I'm looking for good first issues as I want to contribute to MindDB. @paxcema \n\nHi @Birger9, I believe it is but not 100% sure. There are instructions above to replicate the issue. If you run into it, feel free to work on a solution, simply let us know and we can assign you 😄 \n\n> ### Short description of current behavior\r\n> In the process of contributing new ML engines, @sammiller06 has suggested we add `__init__.py` files where needed to avoid `ModuleNotFoundError` errors, which I've confirmed are still happening as of #5454.\r\n> \r\n> More context:\r\n> \r\n> > ### PyTest’s classic ModuleNotFoundError\r\n> > I was unable to run the tests in unit/ml_handlers/ on first try as I got the classic “ModuleNotFoundError”. I know from Pytest experience that you need to add **init**.py files to specific subdirectories, but new contributors may find this a confusing blocker.\r\n> > Suggestion: make sure new contributors can run tests locally without adding their own **init**.py files\r\n> \r\n> ### Video or screenshots\r\n> _No response_\r\n> \r\n> ### Expected behavior\r\n> _No response_\r\n> \r\n> ### How to reproduce the error\r\n> _No response_\r\n> \r\n> ### Anything else?\r\n> _No response_\r\n\r\nTo address the issue described, you need to ensure that the `__init__.py` files are present in the appropriate directories so that Python treats them as packages. Here's an example of how you can add these files to the specified subdirectories:\r\n\r\n```bash\r\ntouch unit/ml_handlers/__init__.py\r\n```\r\n\r\nYou can run this command in your project's root directory to create an empty `__init__.py` file in the `unit/ml_handlers/` directory. This will make Python recognize `unit/ml_handlers/` as a package, and you should no longer encounter `ModuleNotFoundError` errors when running tests in that directory.\r\n\r\nRepeat the same process for any other directories that require `__init__.py` files to be added to address similar import issues.\n\nHi @paxcema, I just try to address this issue to get the hang of contributing. It seems like the  file `pytest`  from command `python -m  pytest` is not there, and each subfolder  of ` ./test` already have the `.init` file, so do I miss something ?\n\nHey @nguyenbanhducA1K51, looking at the updated `staging` branch of the repo now and you're right. I will close this since it seems to have been solved, tests are being collected correctly now. \r\n\r\nThanks anyway! I encourage you to look for other open issues.",
  "pr_link": "https://github.com/mindsdb/mindsdb/pull/6166",
  "code_context": [
    {
      "filename": "tests/__init__.py",
      "content": ""
    }
  ]
}